In [2]:
from pathlib import Path
import pandas as pd

In [4]:
file_path = Path("../data/raw/Telco_customer_churn.xlsx")

In [5]:
file_path.exists()

True

In [6]:
xls = pd.ExcelFile(file_path)
xls.sheet_names

['Telco_Churn']

In [9]:
df = pd.read_excel(file_path, sheet_name="Telco_Churn")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [10]:
df.shape

(7043, 33)

In [11]:
df.columns.tolist()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [22]:
df.sample(10)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2644,3524-WQDSG,1,United States,California,Corte Madera,94925,"37.924014, -122.511694",37.924014,-122.511694,Female,...,Month-to-month,Yes,Bank transfer (automatic),99.30,4209.95,No,0,73,3280,NaN
540,8305-VHZBZ,1,United States,California,San Diego,92154,"32.578103, -117.012975",32.578103,-117.012975,Male,...,Month-to-month,Yes,Mailed check,20.20,20.2,Yes,1,92,4325,Product dissatisfaction
4677,6701-YVNQG,1,United States,California,Moreno Valley,92553,"33.923149, -117.244933",33.923149,-117.244933,Male,...,Two year,Yes,Credit card (automatic),88.70,6301.7,No,0,41,5764,NaN
1725,3190-XFANI,1,United States,California,Happy Camp,96039,"41.831901, -123.487478",41.831901,-123.487478,Male,...,One year,Yes,Bank transfer (automatic),100.60,5069.65,Yes,1,82,5585,Competitor offered more data
4086,6620-JDYNW,1,United States,California,Leggett,95585,"39.873371, -123.741474",39.873371,-123.741474,Female,...,Month-to-month,Yes,Mailed check,60.60,1156.35,No,0,74,4459,NaN
3367,3546-GHEAE,1,United States,California,Blythe,92225,"33.674583, -114.71612",33.674583,-114.716120,Male,...,Two year,No,Mailed check,19.45,165.35,No,0,42,2600,NaN
6116,1539-LNKHM,1,United States,California,Orange Cove,93646,"36.633498, -119.298895",36.633498,-119.298895,Female,...,Month-to-month,No,Mailed check,20.40,266.6,No,0,60,4497,NaN
4245,3594-IVHJZ,1,United States,California,French Gulch,96033,"40.740138, -122.587476",40.740138,-122.587476,Female,...,Month-to-month,Yes,Mailed check,20.45,42.45,No,0,56,2606,NaN
1255,9300-AGZNL,1,United States,California,Elk Creek,95939,"39.53222, -122.594879",39.532220,-122.594879,Male,...,Month-to-month,Yes,Electronic check,94.00,94,Yes,1,67,4176,Product dissatisfaction
6539,1025-FALIX,1,United States,California,Nicolaus,95659,"38.788898, -121.608624",38.788898,-121.608624,Female,...,Month-to-month,Yes,Credit card (automatic),69.05,1815.65,No,0,23,5379,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

## Business columns

In [18]:
df[["Tenure Months", "Monthly Charges", "Contract", "Total Charges", "Payment Method", "Paperless Billing"]].sample(10)

,Tenure Months,Monthly Charges,Contract,Total Charges,Payment Method,Paperless Billing
1476,9,94.85,Month-to-month,890.6,Mailed check,Yes
6100,2,19.90,Month-to-month,33.7,Credit card (automatic),Yes
1128,14,89.80,Month-to-month,1129.1,Mailed check,Yes
4373,26,61.55,One year,1581.95,Electronic check,No
2531,27,110.50,One year,2857.6,Bank transfer (automatic),Yes
5299,1,70.70,Month-to-month,70.7,Mailed check,Yes
5195,8,66.05,Month-to-month,574.5,Bank transfer (automatic),No
1288,4,46.00,Month-to-month,181.6,Electronic check,No
5078,7,20.35,Month-to-month,150.6,Mailed check,No
4546,23,55.30,Month-to-month,1284.2,Bank transfer (automatic),Yes

## service-related features

In [20]:
df[["Phone Service", "Multiple Lines", "Internet Service", "Online Security", "Online Backup", "Device Protection", "Tech Support", "Streaming TV", "Streaming Movies"]].sample(10)

,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies
175,Yes,No,DSL,No,No,Yes,No,No,No
4920,Yes,Yes,Fiber optic,No,Yes,No,No,No,No
6460,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes
6754,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
1759,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No
2965,Yes,No,DSL,Yes,Yes,No,Yes,No,No
1234,Yes,Yes,Fiber optic,No,No,No,No,No,Yes
6442,Yes,No,Fiber optic,Yes,Yes,No,No,No,No
1095,No,No phone service,DSL,No,No,No,Yes,No,No
822,Yes,No,DSL,No,No,No,No,No,No

## Household/ demographic features

In [21]:
df[["Gender", "Senior Citizen", "Partner", "Dependents"]].sample(10)

      Gender Senior Citizen Partner Dependents
4580    Male             No     Yes         No
4647  Female             No     Yes         No
4220  Female             No     Yes        Yes
5187  Female             No     Yes        Yes
5830  Female             No     Yes        Yes
2197    Male             No     Yes         No
1898  Female             No      No         No
2505  Female             No     Yes        Yes
6932    Male             No      No         No
864   Female             No      No         No

In [23]:
df["Churn Label"].value_counts()

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [24]:
df["Churn Label"].value_counts(normalize=True)

Churn Label
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [25]:
pd.crosstab(df["Churn Label"], df["Churn Value"])

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [26]:
df["Total Charges"].head(10)

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: object

In [27]:
df["Total Charges"].isna().sum()

0

In [28]:
(df["Total Charges"] == " ").sum()

11

In [29]:
df[df["Total Charges"] == " "]

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [30]:
df.loc[df["Total Charges"] == " ", "Tenure Months"]

2234    0
2438    0
2568    0
2667    0
2856    0
4331    0
4687    0
5104    0
5719    0
6772    0
6840    0
Name: Tenure Months, dtype: int64

In [32]:
df.loc[df['Total Charges'] == " ", 'Tenure Months'].value_counts()

Tenure Months
0    11
Name: count, dtype: int64

In [ ]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce") #'coerce' will convert non-numeric values to NaN
# 'ignore' option will leave non-numeric values as they are, which can lead to issues in analysis and modeling
# 'raise' option will raise an error if non-numeric values are encountered, which can help identify and address data quality issues early on

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7032 non-null   float64
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

In [36]:
df["Total Charges"].isna().sum()

11

In [37]:
df[["Tenure Months", "Monthly Charges", "Total Charges"]].describe()

       Tenure Months  Monthly Charges  Total Charges
count    7043.000000      7043.000000    7032.000000
mean       32.371149        64.761692    2283.300441
std        24.559481        30.090047    2266.771362
min         0.000000        18.250000      18.800000
25%         9.000000        35.500000     401.450000
50%        29.000000        70.350000    1397.475000
75%        55.000000        89.850000    3794.737500
max        72.000000       118.750000    8684.800000