In [2]:
from pathlib import Path
import pandas as pd

In [3]:
file_path = Path("../data/raw/Telco_customer_churn.xlsx")

In [4]:
file_path.exists()

True

In [5]:
xls = pd.ExcelFile(file_path)
xls.sheet_names

['Telco_Churn']

In [6]:
df = pd.read_excel(file_path, sheet_name="Telco_Churn")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [7]:
df.shape

(7043, 33)

In [8]:
df.columns.tolist()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [9]:
df.sample(10)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
3605,2789-HQBOU,1,United States,California,Bakersfield,93306,"35.449881, -118.841442",35.449881,-118.841442,Male,...,Month-to-month,Yes,Electronic check,80.35,253.8,No,0,51,4203,NaN
1968,2639-UGMAZ,1,United States,California,Artesia,90701,"33.867593, -118.080637",33.867593,-118.080637,Male,...,One year,Yes,Electronic check,56.45,3985.35,No,0,68,5372,NaN
5799,7901-IIDQV,1,United States,California,San Diego,92119,"32.802959, -117.027095",32.802959,-117.027095,Male,...,One year,No,Bank transfer (automatic),54.60,1242.25,No,0,51,3398,NaN
6453,6394-HHHZM,1,United States,California,Little River,95456,"39.245911, -123.77214",39.245911,-123.772140,Male,...,Month-to-month,No,Mailed check,20.70,57.5,No,0,23,2011,NaN
4532,9987-LUTYD,1,United States,California,La Mesa,91941,"32.759327, -116.99726",32.759327,-116.997260,Female,...,One year,No,Mailed check,55.15,742.9,No,0,59,3161,NaN
3108,0354-VXMJC,1,United States,California,Los Angeles,90034,"34.030578, -118.399613",34.030578,-118.399613,Male,...,Two year,No,Credit card (automatic),19.60,426.65,No,0,35,4617,NaN
783,9685-WKZGT,1,United States,California,Carmichael,95608,"38.626128, -121.328011",38.626128,-121.328011,Male,...,Month-to-month,Yes,Electronic check,74.95,1036.75,Yes,1,70,2075,Extra data charges
651,8433-WXGNA,1,United States,California,Salinas,93906,"36.722898, -121.633648",36.722898,-121.633648,Male,...,Month-to-month,Yes,Electronic check,75.70,189.2,Yes,1,82,4676,Don't know
436,7963-GQRMY,1,United States,California,Los Angeles,90004,"34.076259, -118.310715",34.076259,-118.310715,Female,...,Month-to-month,No,Mailed check,44.30,134.5,Yes,1,88,4903,Extra data charges
2035,2040-LDIWQ,1,United States,California,Woodland Hills,91367,"34.178068, -118.615714",34.178068,-118.615714,Male,...,Two year,Yes,Bank transfer (automatic),84.20,5324.5,No,0,33,5256,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

## Business columns

In [11]:
df[["Tenure Months", "Monthly Charges", "Contract", "Total Charges", "Payment Method", "Paperless Billing"]].sample(10)

,Tenure Months,Monthly Charges,Contract,Total Charges,Payment Method,Paperless Billing
828,9,44.95,Month-to-month,431,Mailed check,No
1797,4,74.95,Month-to-month,308.7,Electronic check,No
4456,44,54.00,One year,2440.25,Electronic check,Yes
6204,12,24.00,Two year,269.65,Bank transfer (automatic),Yes
1062,20,24.45,Month-to-month,482.8,Electronic check,Yes
2844,60,65.85,One year,3928.3,Bank transfer (automatic),Yes
3077,68,84.40,Two year,5746.75,Credit card (automatic),Yes
6741,25,55.55,Month-to-month,1405.3,Credit card (automatic),No
5653,2,72.60,Month-to-month,154.3,Mailed check,Yes
3793,71,109.60,One year,7854.15,Electronic check,Yes

## service-related features

In [12]:
df[["Phone Service", "Multiple Lines", "Internet Service", "Online Security", "Online Backup", "Device Protection", "Tech Support", "Streaming TV", "Streaming Movies"]].sample(10)

,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies
641,Yes,Yes,Fiber optic,No,No,No,No,No,No
5796,Yes,No,Fiber optic,Yes,Yes,No,Yes,Yes,Yes
909,Yes,Yes,Fiber optic,No,No,No,No,No,No
4491,Yes,Yes,Fiber optic,Yes,No,No,Yes,No,Yes
3039,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
1581,Yes,Yes,Fiber optic,No,No,No,No,No,Yes
3629,No,No phone service,DSL,Yes,Yes,No,Yes,No,No
1522,Yes,No,Fiber optic,No,No,No,No,No,No
4413,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes
2443,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service

## Household/ demographic features

In [13]:
df[["Gender", "Senior Citizen", "Partner", "Dependents"]].sample(10)

      Gender Senior Citizen Partner Dependents
6471    Male            Yes     Yes         No
2154    Male             No      No         No
5043  Female             No     Yes         No
4169  Female            Yes     Yes        Yes
1209    Male             No      No         No
2089  Female             No     Yes        Yes
2638    Male             No     Yes        Yes
4012  Female            Yes      No         No
2379  Female            Yes      No         No
6052    Male             No      No         No

In [14]:
df["Churn Label"].value_counts()

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [15]:
df["Churn Label"].value_counts(normalize=True)

Churn Label
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [16]:
pd.crosstab(df["Churn Label"], df["Churn Value"])

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [17]:
df["Total Charges"].head(10)

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: object

In [18]:
df["Total Charges"].isna().sum()

0

In [19]:
(df["Total Charges"] == " ").sum()

11

In [20]:
df[df["Total Charges"] == " "]

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [21]:
df.loc[df["Total Charges"] == " ", "Tenure Months"]

2234    0
2438    0
2568    0
2667    0
2856    0
4331    0
4687    0
5104    0
5719    0
6772    0
6840    0
Name: Tenure Months, dtype: int64

In [22]:
df.loc[df['Total Charges'] == " ", 'Tenure Months'].value_counts()

Tenure Months
0    11
Name: count, dtype: int64

In [23]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce") #'coerce' will convert non-numeric values to NaN
# 'ignore' option will leave non-numeric values as they are, which can lead to issues in analysis and modeling
# 'raise' option will raise an error if non-numeric values are encountered, which can help identify and address data quality issues early on

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7032 non-null   float64
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

In [25]:
df["Total Charges"].isna().sum()

11

In [26]:
df[["Tenure Months", "Monthly Charges", "Total Charges"]].describe()

       Tenure Months  Monthly Charges  Total Charges
count    7043.000000      7043.000000    7032.000000
mean       32.371149        64.761692    2283.300441
std        24.559481        30.090047    2266.771362
min         0.000000        18.250000      18.800000
25%         9.000000        35.500000     401.450000
50%        29.000000        70.350000    1397.475000
75%        55.000000        89.850000    3794.737500
max        72.000000       118.750000    8684.800000

In [27]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- CustomerID ---
CustomerID
3668-QPYBK    1
9169-BSVIN    1
0206-OYVOC    1
6418-HNFED    1
8805-JNRAZ    1
             ..
6797-UCJHZ    1
5016-IBERQ    1
3003-CMDUU    1
5148-HKFIR    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- Country ---
Country
United States    7043
Name: count, dtype: int64

--- State ---
State
California    7043
Name: count, dtype: int64

--- City ---
City
Los Angeles       305
San Diego         150
San Jose          112
Sacramento        108
San Francisco     104
                 ...
Healdsburg          4
Jenner              4
Philo               4
Point Arena         4
Olympic Valley      4
Name: count, Length: 1129, dtype: int64

--- Lat Long ---
Lat Long
33.964131, -118.272783    5
34.152875, -118.486056    5
32.912664, -116.635387    5
32.64164, -116.985026     5
32.607964, -117.059459    5
                         ..
37.4695, -120.672724      4
38.055562, -120.456298    4
38.244806, -120.417301    4
38.264262, -120.515133    4
39.191797, -120.212401    4
Name: count, Length: 1652, dtype: int64

--- Gender ---
Gender
Male      3555
Female    3488
Name: count, dtype: int64

--- Senior Citizen ---
Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64

--- Partner ---
Partner
No     3641
Yes    3402
Name: count, dtype: int64

--- Dependents ---
Dependents
No     5416
Yes    1627
Name: count, dtype: int64

--- Phone Service ---
Phone Service
Yes    6361
No      682
Name: count, dtype: int64

--- Multiple Lines ---
Multiple Lines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- Internet Service ---
Internet Service
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

--- Online Security ---
Online Security
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

--- Online Backup ---
Online Backup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- Device Protection ---
Device Protection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

--- Tech Support ---
Tech Support
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

--- Streaming TV ---
Streaming TV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

--- Streaming Movies ---
Streaming Movies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

--- Contract ---
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- Paperless Billing ---
Paperless Billing
Yes    4171
No     2872
Name: count, dtype: int64

--- Payment Method ---
Payment Method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- Churn Label ---
Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

--- Churn Reason ---
Churn Reason
NaN                                          5174
Attitude of support person                    192
Competitor offered higher download speeds     189
Competitor offered more data                  162
Don't know                                    154
Competitor made better offer                  140
Attitude of service provider                  135
Competitor had better devices                 130
Network reliability                           103
Product dissatisfaction                       102
Price too high                                 98
Service dissatisfaction                        89
Lack of self-service on Website                88
Extra data charges                             57
Moved                                          53
Lack of affordable download/upload speed       44
Long distance charges                          44
Limited range of services                      44
Poor expertise of phone support                20
Poor expertise of online support               19
Deceased                                        6
Name: count, dtype: int64

In [28]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
numeric_cols.tolist()

['Count',
 'Zip Code',
 'Latitude',
 'Longitude',
 'Tenure Months',
 'Monthly Charges',
 'Total Charges',
 'Churn Value',
 'Churn Score',
 'CLTV']

In [29]:
df["CLTV"].describe()

count    7043.000000
mean     4400.295755
std      1183.057152
min      2003.000000
25%      3469.000000
50%      4527.000000
75%      5380.500000
max      6500.000000
Name: CLTV, dtype: float64

In [30]:
df["Count"].value_counts(dropna=False)

Count
1    7043
Name: count, dtype: int64

In [31]:
df["Zip Code"].nunique()

1652

In [32]:
df["CustomerID"].nunique()

7043

In [33]:
df["Churn Reason"].notna().sum()

1869

In [34]:
df["Churn Label"].value_counts(dropna=False)

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [35]:
pd.crosstab(df["Churn Label"], df["Churn Reason"].notna())

Churn Reason  False  True
Churn Label
No             5174      0
Yes               0   1869

In [36]:
df.groupby("Churn Label")["Churn Score"].describe()

              count       mean        std   min   25%   50%   75%    max
Churn Label
No           5174.0  50.098183  17.702277   5.0  35.0  50.0  66.0   80.0
Yes          1869.0  82.510433  10.328570  65.0  74.0  82.0  91.0  100.0

In [37]:
df.groupby("Churn Label")["CLTV"].describe()

,count,mean,std,min,25%,50%,75%,max
Churn Label,,,,,,,,
No,5174.0,4490.921337,1167.703198,2003.0,3643.75,4620.0,5434.75,6500.0
Yes,1869.0,4149.414660,1189.370707,2003.0,3101.00,4238.0,5166.00,6484.0

In [38]:
drop_cols = [
    "CustomerID",
    "Count",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Lat Long",
    "Latitude",
    "Longitude",
    "Churn Label",
    "Churn Score",
    "CLTV",
    "Churn Reason"
]

keep_for_now = [col for col in df.columns if col not in drop_cols]

keep_for_now

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Value']

In [39]:
model_df = df[keep_for_now].copy()
model_df.shape

(7043, 20)

In [40]:
model_df.isna().sum()

Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Value           0
dtype: int64

In [41]:
model_df["Total Charges"].isna().mean()

0.001561834445548772

In [42]:
model_df[model_df["Total Charges"].isna()]

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
2234,Female,No,Yes,No,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,0
2438,Male,No,No,No,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,0
2568,Female,No,Yes,No,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,0
2667,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,0
2856,Female,No,Yes,No,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,0
4331,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,0
4687,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,0
5104,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,0
5719,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,0
6772,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,0
6840,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,0

In [43]:
model_df["Total Charges"] = model_df["Total Charges"].fillna(0)

In [44]:
model_df["Total Charges"].isna().sum()

0

In [ ]:
X = model_df.drop(columns=["Churn Value"]) # another way to do this is: X = model_df.loc[:, model_df.columns != "Churn Value"]
y = model_df["Churn Value"]

In [46]:
X.shape, y.shape

((7043, 19), (7043,))

In [47]:
X.dtypes

Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
dtype: object

In [48]:
X.select_dtypes(include="object").columns.tolist(), X.select_dtypes(exclude="object").columns.tolist()

(['Gender',
  'Senior Citizen',
  'Partner',
  'Dependents',
  'Phone Service',
  'Multiple Lines',
  'Internet Service',
  'Online Security',
  'Online Backup',
  'Device Protection',
  'Tech Support',
  'Streaming TV',
  'Streaming Movies',
  'Contract',
  'Paperless Billing',
  'Payment Method'],
 ['Tenure Months', 'Monthly Charges', 'Total Charges'])

In [51]:
X.select_dtypes(include="object").columns.tolist()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method']

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5634, 19), (1409, 19), (5634,), (1409,))

In [56]:
y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(Churn Value
 0    0.734647
 1    0.265353
 Name: proportion, dtype: float64,
 Churn Value
 0    0.734564
 1    0.265436
 Name: proportion, dtype: float64)

In [57]:
categorical_cols = X_train.select_dtypes(include="object").columns.tolist()
numeric_cols = X_train.select_dtypes(exclude="object").columns.tolist()

categorical_cols, numeric_cols

(['Gender',
  'Senior Citizen',
  'Partner',
  'Dependents',
  'Phone Service',
  'Multiple Lines',
  'Internet Service',
  'Online Security',
  'Online Backup',
  'Device Protection',
  'Tech Support',
  'Streaming TV',
  'Streaming Movies',
  'Contract',
  'Paperless Billing',
  'Payment Method'],
 ['Tenure Months', 'Monthly Charges', 'Total Charges'])

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [59]:
preprocessor = ColumnTransformer(
    transformers = [
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

In [60]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, random_state=42)